/** @format */

export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAILURE = "GET_ALL_ORDERS_FAILURE";

export const GET_DETAIL_ORDER_REQUEST = "GET_DETAIL_ORDER_REQUEST";
export const GET_DETAIL_ORDER_SUCCESS = "GET_DETAIL_ORDER_SUCCESS";
export const GET_DETAIL_ORDER_FAILURE = "GET_DETAIL_ORDER_FAILURE";

export const UPDATE_STATUS_ORDER_REQUEST = "UPDATE_STATUS_ORDER_REQUEST";
export const UPDATE_STATUS_ORDER_SUCCESS = "UPDATE_STATUS_ORDER_SUCCESS";
export const UPDATE_STATUS_ORDER_FAILURE = "UPDATE_STATUS_ORDER_FAILURE";

export const GET_ALL_ORDERS_FILTER_REQUEST = "GET_ALL_ORDERS_FILTER_REQUEST";
export const GET_ALL_ORDERS_FILTER_SUCCESS = "GET_ALL_ORDERS_FILTER_SUCCESS";
export const GET_ALL_ORDERS_FILTER_FAILURE = "GET_ALL_ORDERS_FILTER_FAILURE";

export const GET_ALL_ORDERS_STATUS_REQUEST = "GET_ALL_ORDERS_STATUS_REQUEST";
export const GET_ALL_ORDERS_STATUS_SUCCESS = "GET_ALL_ORDERS_STATUS_SUCCESS";
export const GET_ALL_ORDERS_STATUS_FAILURE = "GET_ALL_ORDERS_STATUS_FAILURE";
