/** @format */

export const GET_ALL_PRODUCER_REQUEST = "GET_ALL_PRODUCER_REQUEST";
export const GET_ALL_PRODUCER_SUCCESS = "GET_ALL_PRODUCER_SUCCESS";
export const GET_ALL_PRODUCER_FAILURE = "GET_ALL_PRODUCER_FAILURE";

export const CREATE_PRODUCER_REQUEST = "CREATE_PRODUCER_REQUEST";
export const CREATE_PRODUCER_SUCCESS = "CREATE_PRODUCER_SUCCESS";
export const CREATE_PRODUCER_FAILURE = "CREATE_PRODUCER_FAILURE";
