/** @format */

export const GET_INTERVAL_SIX_MONTH_REQUEST = "GET_INTERVAL_SIX_MONTH_REQUEST";
export const GET_INTERVAL_SIX_MONTH_SUCCESS = "GET_INTERVAL_SIX_MONTH_SUCCESS";
export const GET_INTERVAL_SIX_MONTH_FAILURE = "GET_INTERVAL_SIX_MONTH_FAILURE";

export const GET_ALL_DAY_IN_MONTH_REQUEST = "GET_ALL_DAY_IN_MONTH_REQUEST";
export const GET_ALL_DAY_IN_MONTH_SUCCESS = "GET_ALL_DAY_IN_MONTH_SUCCESS";
export const GET_ALL_DAY_IN_MONTH_FAILURE = "GET_ALL_DAY_IN_MONTH_FAILURE";

export const GET_ALL_WEEK_IN_YEAR_REQUEST = "GET_ALL_WEEK_IN_YEAR_REQUEST";
export const GET_ALL_WEEK_IN_YEAR_SUCCESS = "GET_ALL_WEEK_IN_YEAR_SUCCESS";
export const GET_ALL_WEEK_IN_YEAR_FAILURE = "GET_ALL_WEEK_IN_YEAR_FAILURE";

export const GET_ALL_MONTH_IN_YEAR_REQUEST = "GET_ALL_MONTH_IN_YEAR_REQUEST";
export const GET_ALL_MONTH_IN_YEAR_SUCCESS = "GET_ALL_MONTH_IN_YEAR_SUCCESS";
export const GET_ALL_MONTH_IN_YEAR_FAILURE = "GET_ALL_MONTH_IN_YEAR_FAILURE";
