/** @format */

export const GET_INTERVAL_SIX_MONTH_REQUEST = "GET_INTERVAL_SIX_MONTH_REQUEST";
export const GET_INTERVAL_SIX_MONTH_SUCCESS = "GET_INTERVAL_SIX_MONTH_SUCCESS";
export const GET_INTERVAL_SIX_MONTH_FAILURE = "GET_INTERVAL_SIX_MONTH_FAILURE";
