/** @format */

export const CREATE_SALE_REQUEST = "CREATE_SALE_REQUEST";
export const CREATE_SALE_SUCCESS = "CREATE_SALE_SUCCESS";
export const CREATE_SALE_FAILURE = "CREATE_SALE_FAILURE";

export const GET_ALL_SALE_REQUEST = "GET_ALL_SALE_REQUEST";
export const GET_ALL_SALE_SUCCESS = "GET_ALL_SALE_SUCCESS";
export const GET_ALL_SALE_FAILURE = "GET_ALL_SALE_FAILURE";
